### ISSUE TITLE
Breaking change in langchain-google-genai after version from 1.0.3 -> 1.0.4 or higher gives 'TypeError: generate_content() got an unexpected keyword argument 'request'

### ISSUE THREAD

**Issue by namitharajb** [langchain-ai/langchain-google#296]
Hi,
We are using langchain-google-genai   in our AI sdk and for langchain integration of gemini model, we use langchain-google-genai, which was working fine with version 1.0.3 and as soon as I update it to version 1.0.4 or higher I get below error from chat_models.py:187: in _chat_with_retry.

Previously we had following library version:
```
langchain~=0.1.16 
google-generativeai~=0.5.4 
langchain-google-genai==1.0.3 
```

now when I update to :
```
langchain[openai]~=0.2.1 
google-generativeai~=0.5.4 
langchain-google-genai==1.0.4
```

This request parameter is added in https://github.com/langchain-ai/langchain-google/blob/f11446a743f104703ddd9bac811a4527a85ae90a/libs/genai/langchain_google_genai/chat_models.py#L760

The version 1.0.3 worked as expected but not in version 1.0.4 or higher and I see there was a refactoring done, could you please let me know if there is any change in the way we invoke the chain or initialize the model is exactly like before. 

It looks like the refactoring https://github.com/langchain-ai/langchain-google/pull/209/files#diff-789e24521c3e983e4ad9f51a1c0db73ea6fe0e36a60609b2d20026b106c4b813 has caused breaking changes.

>  chat_model = ChatGoogleGenerativeAI(proxy_model_name='gemini-1.0-pro', proxy_client=self.proxy_client)
>         self.assertIsNotNone(chat_model.model)
>         tweet_prompt = PromptTemplate.from_template("You are a content creator. Write me a tweet about {topic}.")
>         chain = LLMChain(llm=chat_model, prompt=tweet_prompt, verbose=True)
> >       response = chain.invoke('How does it feel to experience snow in summer?')
> 
> test_google.py:44: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> ../../ENV/lib/python3.9/site-packages/langchain/chains/base.py:166: in invoke
>     raise e
> ../../ENV/lib/python3.9/site-packages/langchain/chains/base.py:156: in invoke
>     self._call(inputs, run_manager=run_manager)
> ../../ENV/lib/python3.9/site-packages/langchain/chains/llm.py:126: in _call
>     response = self.generate([inputs], run_manager=run_manager)
> ../../ENV/lib/python3.9/site-packages/langchain/chains/llm.py:138: in generate
>     return self.llm.generate_prompt(
> ../../ENV/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py:599: in generate_prompt
>     return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
> ../../ENV/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py:456: in generate
>     raise e
> ../../ENV/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py:446: in generate
>     self._generate_with_cache(
> ../../ENV/lib/python3.9/site-packages/langchain_core/language_models/chat_models.py:671: in _generate_with_cache
>     result = self._generate(
> ../../ENV/lib/python3.9/site-packages/langchain_google_genai/chat_models.py:760: in _generate
>     response: GenerateContentResponse = _chat_with_retry(
> ../../ENV/lib/python3.9/site-packages/langchain_google_genai/chat_models.py:189: in _chat_with_retry
>     return _chat_with_retry(**kwargs)
> ../../ENV/lib/python3.9/site-packages/tenacity/__init__.py:289: in wrapped_f
>     return self(f, *args, **kw)
> ../../ENV/lib/python3.9/site-packages/tenacity/__init__.py:379: in __call__
>     do = self.iter(retry_state=retry_state)
> ../../ENV/lib/python3.9/site-packages/tenacity/__init__.py:314: in iter
>     return fut.result()
> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py:438: in result
>     return self.__get_result()
> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py:390: in __get_result
>     raise self._exception
> ../../ENV/lib/python3.9/site-packages/tenacity/__init__.py:382: in __call__
>     result = fn(*args, **kwargs)
> ../../ENV/lib/python3.9/site-packages/langchain_google_genai/chat_models.py:187: in _chat_with_retry
>     raise e
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> kwargs = {'metadata': [], 'request': model: "gemini-1.0-pro"
> contents {
>   parts {
>     text: "You are a content creator. Write m...loods affect Heidelberg, Germany."
>   }
>   role: "user"
> }
> generation_config {
>   candidate_count: 1
>   temperature: 0.7
> }
> }
> 
>     @retry_decorator
>     def _chat_with_retry(**kwargs: Any) -> Any:
>         try:
> >           return generation_method(**kwargs)
> E           TypeError: generate_content() got an unexpected keyword argument 'request'
> 
> ../../ENV/lib/python3.9/site-packages/langchain_google_genai/chat_models.py:171: TypeError

**Comment by namitharajb** [comment]
@lkuligin I see that the refactoring was done by you. It would be great if you could take a look at this issue as this is blocking us from using latest langchain and langchain-google versions.

**Comment by lkuligin** [comment]
It looks like you're doing some additional transformations on your side.

This code works fine with the latest version of libraries:
```
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key=api_key)

from langchain_core.prompts.prompt import PromptTemplate
from langchain.chains import LLMChain
 
tweet_prompt = PromptTemplate.from_template("You are a content creator. Write me a tweet about {topic}.")
chain = LLMChain(llm=llm, prompt=tweet_prompt, verbose=True)

response = chain.invoke('How does it feel to experience snow in summer?')
print(response)
```

**Comment by lkuligin** [comment]
so essentially there're no breaking changes to the standard interfaces, if you're using low-level private methods, maybe you need to adjust things on your side accordingly, but I'm not sure it can be treated as a "breaking change".

**Comment by namitharajb** [comment]
@lkuligin There hasn't been any code changes in our sdk where we use langchain-google, the above error is caused only when I upgrade the library to version 1.0.4 or higher. If I use 1.0.3 the "invoke" call works fine.

The argument "request" in the error is also something that is added within langchain_google_genai and not from our code. 

```
E TypeError: generate_content() got an unexpected keyword argument 'request'

../../ENV/lib/python3.9/site-packages/langchain_google_genai/chat_models.py:171: TypeError
```
This request attribute is set within https://github.com/langchain-ai/langchain-google/blob/f11446a743f104703ddd9bac811a4527a85ae90a/libs/genai/langchain_google_genai/chat_models.py#L760

**Comment by namitharajb** [comment]
Hi,
To give more information on where the breaking changes is -> https://github.com/langchain-ai/langchain-google/pull/207/files#diff-789e24521c3e983e4ad9f51a1c0db73ea6fe0e36a60609b2d20026b106c4b813
With this refactoring in chat_models.py, the client part of the ChatGoogleGenerativeAI is "GenerativeServiceClient" instead of "GenerativeModel" 
Since, we need provide our Authorization via request headers, we have a overridden class for GenerativeModel class, which is also the native google client "google.generativeai.GenerativeModel" from "google-generativeai" library. With older version this client was compatible due to above reason. Whereas with newer version with change in client, it requires to add authorization and URI for the new client. Since the existing library doesn't support passing these parameters for Authorization, it requires to re-write some of the implementation, making it quite difficult to integrate.
Could we know the reaon for changing the client from "GenerativeModel" to "GenerativeServiceClient" in ChatGoogleGenerativeAI class?

Thanks,
Namitha
